http:
  port: 8080

admin:
  port: 9876
  host: localhost
apiEndpoints:
  graphql:
    host: localhost
    paths: ["/graphql"]
    methods: "*"
  grpc:
    host: localhost
    paths: ["/user-api-docs", "/users", "/users/:id", "/users/*"]
    methods: "*"
  kafka:
    host: localhost
    paths: ["/send", "/notifications", "/notification-api-docs"]
    methods: "*"
serviceEndpoints:
  graphqlService:
    url: "http://localhost:4000/graphql"
  grpcService:
    url: "http://localhost:8000"
  kafkaService:
    url: "http://localhost:9096"
policies:
  - cors
  - proxy
pipelines:
  graphqlPipeline:
    apiEndpoints:
      - graphql
    policies:
      - cors:
          - action:
              origin: "http://localhost:3000"
              methods: "HEAD,PUT,PATCH,POST,DELETE"
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: graphqlService
              changeOrigin: true
  grpcPipeline:
    apiEndpoints:
      - grpc
    policies:
      - cors:
          - action:
              origin: "http://localhost:3000"
              methods: "HEAD,PUT,PATCH,POST,DELETE"
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: grpcService
              changeOrigin: true
  kafkaPipeline:
    apiEndpoints:
      - kafka
    policies:
      - cors:
          - action:
              origin: "http://localhost:3000"
              methods: "HEAD,PUT,PATCH,POST,DELETE"
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: kafkaService
              changeOrigin: true
