http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  graphql:
    host: localhost
    paths: "/graphql"
  grpc:
    host: localhost
    paths: ["/users", "/users/*"]
serviceEndpoints:
  graphqlService:
    url: "http://localhost:4000/graphql" # Assuming your GraphQL server is running on port 4000
  grpcService:
    url: "http://localhost:8000"
policies:
  - cors
  - proxy
pipelines:
  graphqlPipeline:
    apiEndpoints:
      - graphql
    policies:
      - cors: {}
      - proxy:
          - action:
              serviceEndpoint: graphqlService
              changeOrigin: true
  grpcPipeline:
    apiEndpoints:
      - grpc
    policies:
      - proxy:
          - action:
              serviceEndpoint: grpcService
              changeOrigin: true
