http:
  port: 8080
  methods: "*"
  origin: "*"
  credentials: true
  allowedHeaders:
    [
      "Authorization",
      "Content-type",
      "Origin",
      "Access-Control-Allow-Origin",
      "Accept",
      "Options",
      "Access-Control-Request-Headers",
      "Access-Control-Request-Method",
    ]
  exposedHeaders:
    [
      "Content-type",
      "Origin",
      "Access-Control-Allow-Origin",
      "Accept",
      "Options",
      "Access-Control-Request-Headers",
      "Access-Control-Request-Method",
    ]
admin:
  port: 9876
  host: localhost
apiEndpoints:
  graphql:
    host: localhost
    paths: "/graphql"
    methods: "*"
  grpc:
    host: localhost
    paths: ["/users", "/users/:id", "/users/*"]
    methods: "*"
  kafka:
    host: localhost
    paths: ["/send", "/notifications"]
    methods: "*"
serviceEndpoints:
  graphqlService:
    url: "http://localhost:4000/graphql" # Assuming your GraphQL server is running on port 4000
  grpcService:
    url: "http://localhost:8000"
  kafkaService:
    url: "http://localhost:9096"
policies:
  - cors
  - proxy
pipelines:
  graphqlPipeline:
    apiEndpoints:
      - graphql
    policies:
      - cors:
          - action:
              origin: "http://localhost:3000"
              methods: "HEAD,PUT,PATCH,POST,DELETE"
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: graphqlService
              changeOrigin: true
  grpcPipeline:
    apiEndpoints:
      - grpc
    policies:
      - cors:
          - action:
              origin: "http://localhost:3000"
              methods: "HEAD,PUT,PATCH,POST,DELETE"
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: grpcService
              changeOrigin: true
  kafkaPipeline:
    apiEndpoints:
      - kafka
    policies:
      - cors:
          - action:
              origin: "http://localhost:3000"
              methods: "HEAD,PUT,PATCH,POST,DELETE"
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: kafkaService
              changeOrigin: true
